/**
 * Suggestion Engine for LifeOS
 * 
 * Analyzes tasks and generates intelligent suggestions.
 * Pure functions - no side effects, easy to test.
 * 
 * This is a RULE-BASED system (no ML yet):
 * - Pattern matching on task data
 * - Heuristics based on best practices
 * - Scalable as we add more rules
 */

import { daysUntilDue, calculateTaskScore } from "./taskScoring";

type Task = {
  id: string;
  text: string;
  completed: boolean;
  dueDate: string;
  priority: "low" | "medium" | "high";
};

/**
 * Suggestion types represent different kinds of insights
 */
type SuggestionType = 
  | "overdue"           // Task past due date
  | "critical"          // Urgent and high priority
  | "due-today"         // Due now
  | "high-priority-load" // Too many high priority tasks
  | "all-low-priority"  // No high priority tasks set
  | "recommended"       // Next task suggestion
  | "workload-heavy"    // Many tasks pending
  | "good-progress";    // Positive feedback

/**
 * Suggestion severity determines how UI styles it
 */
type SeverityLevel = "critical" | "warning" | "info" | "success";

/**
 * A single suggestion generated by the engine
 */
export type Suggestion = {
  id: string;
  type: SuggestionType;
  message: string;
  detail?: string;
  severity: SeverityLevel;
  taskIds?: string[];    // Which tasks relate to this suggestion
  actionText?: string;   // Optional CTA
  icon?: string;         // Emoji or icon
};

/**
 * ==================== INTERNAL ANALYSIS FUNCTIONS ====================
 */

/**
 * Find all overdue tasks
 */
const findOverdueTasks = (tasks: Task[]): Task[] => {
  return tasks.filter((task) => {
    if (task.completed) return false;
    const days = daysUntilDue(task.dueDate);
    return days < 0; // Past due date
  });
};

/**
 * Find tasks due within X hours
 */
const findTasksDueToday = (tasks: Task[]): Task[] => {
  return tasks.filter((task) => {
    if (task.completed) return false;
    const days = daysUntilDue(task.dueDate);
    return days === 0; // Due today
  });
};

/**
 * Find high priority tasks
 */
const findHighPriorityTasks = (tasks: Task[]): Task[] => {
  return tasks.filter(
    (task) => !task.completed && task.priority === "high"
  );
};

/**
 * Count pending tasks
 */
const countPendingTasks = (tasks: Task[]): number => {
  return tasks.filter((task) => !task.completed).length;
};

/**
 * Get the highest scoring incomplete task (best recommendation)
 */
const getRecommendedTask = (tasks: Task[]): Task | null => {
  const pending = tasks.filter((task) => !task.completed);
  if (pending.length === 0) return null;

  return pending.reduce((best, task) => {
    return calculateTaskScore(task) > calculateTaskScore(best) ? task : best;
  });
};

/**
 * ==================== SUGGESTION GENERATORS ====================
 * Each generator creates suggestions for ONE category
 */

/**
 * Generate suggestions for overdue tasks
 */
const generateOverdueSuggestions = (tasks: Task[]): Suggestion[] => {
  const overdueList = findOverdueTasks(tasks);

  if (overdueList.length === 0) return [];

  const daysOverdue = Math.abs(daysUntilDue(overdueList[0].dueDate));

  return [
    {
      id: "overdue-alert",
      type: "overdue",
      message: `⏰ ${overdueList.length} task${overdueList.length > 1 ? "s" : ""} overdue!`,
      detail: `${overdueList[0].text} is ${daysOverdue} day${daysOverdue > 1 ? "s" : ""} overdue.`,
      severity: "critical",
      taskIds: overdueList.map((t) => t.id),
      actionText: "Complete overdue tasks",
      icon: "⏰",
    },
  ];
};

/**
 * Generate suggestions for tasks due today
 */
const generateDueTodaySuggestions = (tasks: Task[]): Suggestion[] => {
  const todayList = findTasksDueToday(tasks);

  if (todayList.length === 0) return [];

  return [
    {
      id: "due-today-alert",
      type: "due-today",
      message: `📅 ${todayList.length} task${todayList.length > 1 ? "s" : ""} due today!`,
      detail: `Don't forget: ${todayList[0].text}`,
      severity: "warning",
      taskIds: todayList.map((t) => t.id),
      actionText: "Focus on today's tasks",
      icon: "📅",
    },
  ];
};

/**
 * Generate suggestions for high priority overload
 */
const generateHighPrioritySuggestions = (tasks: Task[]): Suggestion[] => {
  const highPriority = findHighPriorityTasks(tasks);
  const pending = tasks.filter((t) => !t.completed);

  if (pending.length === 0) return [];

  const highPrioritypercent = (highPriority.length / pending.length) * 100;

  // Warning: More than 40% of tasks are high priority
  if (highPrioritypercent > 40) {
    return [
      {
        id: "high-priority-load",
        type: "high-priority-load",
        message: `⚠️ Too many high priority tasks!`,
        detail: `${highPriority.length} out of ${pending.length} tasks are marked high priority. Consider deprioritizing some.`,
        severity: "warning",
        taskIds: highPriority.map((t) => t.id),
        actionText: "Review priorities",
        icon: "⚠️",
      },
    ];
  }

  return [];
};

/**
 * Generate suggestions for lack of high priority tasks
 */
const generateNoHighPrioritySuggestions = (tasks: Task[]): Suggestion[] => {
  const highPriority = findHighPriorityTasks(tasks);
  const pending = tasks.filter((t) => !t.completed);

  // Info: No high priority tasks set
  if (pending.length > 0 && highPriority.length === 0) {
    return [
      {
        id: "no-high-priority",
        type: "all-low-priority",
        message: `💡 No high priority tasks set`,
        detail: `Consider prioritizing some tasks to stay focused.`,
        severity: "info",
        icon: "💡",
      },
    ];
  }

  return [];
};

/**
 * Generate suggestions for heavy workload
 */
const generateWorkloadSuggestions = (tasks: Task[]): Suggestion[] => {
  const pending = countPendingTasks(tasks);

  // Warning: More than 15 pending tasks
  if (pending > 15) {
    return [
      {
        id: "heavy-workload",
        type: "workload-heavy",
        message: `📊 Heavy workload: ${pending} pending tasks`,
        detail: `You have a lot on your plate. Consider breaking down tasks or delegating.`,
        severity: "warning",
        icon: "📊",
      },
    ];
  }

  return [];
};

/**
 * Generate recommendation for next task to do
 */
const generateRecommendedSuggestions = (tasks: Task[]): Suggestion[] => {
  const recommended = getRecommendedTask(tasks);

  if (!recommended) return [];

  return [
    {
      id: "recommended-next",
      type: "recommended",
      message: `✨ What to do next:`,
      detail: recommended.text,
      severity: "info",
      taskIds: [recommended.id],
      actionText: "Start this task",
      icon: "✨",
    },
  ];
};

/**
 * Generate positive feedback when user is making progress
 */
const generatePositiveSuggestions = (tasks: Task[]): Suggestion[] => {
  const completed = tasks.filter((t) => t.completed).length;
  const pending = countPendingTasks(tasks);
  const total = tasks.length;

  if (total === 0) return [];

  const completionRate = (completed / total) * 100;

  // Success: User completed all tasks!
  if (pending === 0 && completed > 0) {
    return [
      {
        id: "all-complete",
        type: "good-progress",
        message: `🎉 Congratulations!`,
        detail: `You've completed all tasks! Great job staying organized.`,
        severity: "success",
        icon: "🎉",
      },
    ];
  }

  // Success: High completion rate (>70%)
  if (completionRate > 70 && pending > 0) {
    return [
      {
        id: "good-progress",
        type: "good-progress",
        message: `🚀 You're ${Math.round(completionRate)}% done!`,
        detail: `Keep up the momentum! ${pending} task${pending > 1 ? "s" : ""} remaining.`,
        severity: "success",
        icon: "🚀",
      },
    ];
  }

  return [];
};

/**
 * ==================== MAIN ENGINE FUNCTION ====================
 * This is the PUBLIC API - called by components
 */

/**
 * Generate all suggestions for a task list
 * 
 * This function:
 * 1. Analyzes task data
 * 2. Applies all suggestion rules
 * 3. Returns sorted suggestions (critical first)
 * 
 * IMPORTANT: Order matters!
 * - Critical suggestions first
 * - Then warnings
 * - Then info/success
 */
export const generateSuggestions = (tasks: Task[]): Suggestion[] => {
  if (tasks.length === 0) {
    return [];
  }

  // Generate suggestions from all categories
  const allSuggestions: Suggestion[] = [
    ...generateOverdueSuggestions(tasks),
    ...generateDueTodaySuggestions(tasks),
    ...generateHighPrioritySuggestions(tasks),
    ...generateNoHighPrioritySuggestions(tasks),
    ...generateWorkloadSuggestions(tasks),
    ...generateRecommendedSuggestions(tasks),
    ...generatePositiveSuggestions(tasks),
  ];

  // Sort by severity (critical → warning → info → success)
  const severityOrder = { critical: 0, warning: 1, info: 2, success: 3 };
  allSuggestions.sort(
    (a, b) => severityOrder[a.severity] - severityOrder[b.severity]
  );

  return allSuggestions;
};

/**
 * Utility: Check if a task is mentioned in suggestions
 * Used for highlighting tasks in the UI
 */
export const isTaskHighlightedInSuggestions = (
  taskId: string,
  suggestions: Suggestion[]
): boolean => {
  return suggestions.some((s) => s.taskIds?.includes(taskId));
};

/**
 * Utility: Get UI color based on severity
 */
export const getSuggestionColor = (
  severity: SeverityLevel
): { bg: string; border: string; text: string } => {
  switch (severity) {
    case "critical":
      return {
        bg: "#ffebee",       // Light red
        border: "#ff4444",   // Red
        text: "#c62828",     // Dark red
      };
    case "warning":
      return {
        bg: "#fff3e0",       // Light orange
        border: "#ff9800",   // Orange
        text: "#e65100",     // Dark orange
      };
    case "info":
      return {
        bg: "#e3f2fd",       // Light blue
        border: "#2196f3",   // Blue
        text: "#1565c0",     // Dark blue
      };
    case "success":
      return {
        bg: "#e8f5e9",       // Light green
        border: "#4caf50",   // Green
        text: "#2e7d32",     // Dark green
      };
  }
};
